version: "3.8"

services:
  sender:
    build:
      context: ../
      dockerfile: Dockerfile
    command: "sender.py"
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: localenv-concept
  receiver:
    build:
      context: ../
      dockerfile: Dockerfile
    command: "receiver.py"
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: localenv-concept
