version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.0.4
    env_file:
      - ../.env
    environment:
      - SERVICES=sqs,s3
      - EDGE_PORT=4566
      - EAGER_SERVICE_LOADING=1
      - DEBUG=0
      - PERSISTENCE=1
    ports:
      - '4566:4566'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"